Repository dictation-toolbox/dragonfly, pull requests merged in 2019-12, with the labels that each got.

#181 Add missing DNS parser entry for the special "numeral" word
  dragonfly/engines/backend_natlink/dictation_format.py
Labels: Bug, Dragon NaturallySpeaking, NatLink

#180 Add support for special specifiers to Compound specs
  dragonfly/parsing/grammar.lark
  dragonfly/parsing/parse.py
  dragonfly/test/test_lark_parser.py
Labels: Kaldi, New Feature

#183 Add Window class for Mac OS using AppleScript
  documentation/conf.py
  documentation/window_classes.txt
  dragonfly/windows/darwin_window.py
  dragonfly/windows/window.py
  setup.py
Labels: MacOS, WIP

#184 Update to latest Kaldi 1.2.0
  documentation/kaldi_engine.txt
  dragonfly/engines/backend_kaldi/audio.py
  dragonfly/engines/backend_kaldi/compiler.py
  dragonfly/engines/backend_kaldi/engine.py
  dragonfly/engines/backend_kaldi/kag_version.txt
  dragonfly/examples/kaldi_demo.py
  dragonfly/examples/kaldi_module_loader.py
  dragonfly/examples/kaldi_module_loader_plus.py
  dragonfly/test/test_engine_kaldi.py
Labels: Kaldi, New Feature

#163 Add .pylintrc file & do code cleanup
  .pylintrc
  dragonfly/actions/_test_playsound.py
  dragonfly/actions/_test_startapp.py
  dragonfly/actions/_test_x11_text_key.py
  dragonfly/actions/action_base.py
  dragonfly/actions/action_base_keyboard.py
  dragonfly/actions/action_cmd.py
  dragonfly/actions/action_context.py
  dragonfly/actions/action_function.py
  dragonfly/actions/action_key.py
  dragonfly/actions/action_mimic.py
  dragonfly/actions/action_mouse.py
  dragonfly/actions/action_paste.py
  dragonfly/actions/action_pause.py
  dragonfly/actions/action_playback.py
  dragonfly/actions/action_playsound.py
  dragonfly/actions/action_startapp.py
  dragonfly/actions/action_text.py
  dragonfly/actions/action_waitwindow.py
  dragonfly/actions/keyboard/_base.py
  dragonfly/actions/keyboard/_win32.py
  dragonfly/actions/keyboard/_x11_base.py
  dragonfly/actions/mouse/_win32.py
  dragonfly/actions/sendinput.py
  dragonfly/actions/typeables.py
  dragonfly/grammar/context.py
  dragonfly/grammar/elements_basic.py
  dragonfly/grammar/elements_compound.py
  dragonfly/grammar/grammar_base.py
  dragonfly/grammar/grammar_connection.py
  dragonfly/grammar/list.py
  dragonfly/grammar/recobs.py
  dragonfly/grammar/rule_base.py
  dragonfly/grammar/rule_compound.py
  dragonfly/grammar/rule_mapping.py
  dragonfly/grammar/state.py
  dragonfly/windows/base_window.py
  dragonfly/windows/clipboard.py
  dragonfly/windows/darwin_monitor.py
  dragonfly/windows/fake_window.py
  dragonfly/windows/point.py
  dragonfly/windows/rectangle.py
  dragonfly/windows/win32_monitor.py
  dragonfly/windows/win32_window.py
  dragonfly/windows/window_movers.py
  dragonfly/windows/x11_monitor.py
  dragonfly/windows/x11_window.py
Labels: Documentation, Testing
