Repository dictation-toolbox/dragonfly, pull requests merged in 2019-03, with the labels that each got.

#65 Add `**kwargs` pass-thru in `get_engine()` to pass configs to backend
  dragonfly/engines/__init__.py
Labels: Enhancement

#64 Add optimization for Repetition elements
  documentation/test_grammar_elements_basic_doctest.txt
  dragonfly/engines/backend_natlink/compiler.py
  dragonfly/grammar/elements_basic.py
Labels: Enhancement, NatLink

#67 Add WSR/SAPI5 retain audio support; tweak documentation & gitignore
  .gitignore
  CONTRIBUTING.rst
  documentation/engines.txt
  dragonfly/engines/backend_sapi5/__init__.py
  dragonfly/engines/backend_sapi5/engine.py
Labels: Enhancement, Windows Speech Recognition
