Repository dictation-toolbox/dragonfly, pull requests merged in 2019-04, with the labels that each got.

#62 Rework Pocket Sphinx engine backend
  documentation/engines.txt
  documentation/sphinx_engine.txt
  dragonfly/engines/backend_sphinx/compiler.py
  dragonfly/engines/backend_sphinx/config.py
  dragonfly/engines/backend_sphinx/dragonfly2jsgf.py
  dragonfly/engines/backend_sphinx/engine.py
  dragonfly/engines/backend_sphinx/grammar_wrapper.py
  dragonfly/engines/backend_sphinx/misc.py
  dragonfly/engines/backend_sphinx/recobs.py
  dragonfly/engines/backend_sphinx/recording.py
  dragonfly/engines/backend_sphinx/timer.py
  dragonfly/engines/backend_sphinx/training.py
  dragonfly/examples/_sphinx_engine_example.py
  dragonfly/examples/sphinx_module_loader.py
  dragonfly/examples/sphinx_wave_transcriber.py
  dragonfly/log.py
  dragonfly/test/test_dragonfly2jsgf.py
  dragonfly/test/test_engine_sphinx.py
  dragonfly/test/test_engine_sphinx_dictation.py
Labels: CMU Pocket Sphinx

#70 Add ContextAction class from Aenea
  AUTHORS.txt
  CHANGELOG.rst
  documentation/actions.txt
  dragonfly/__init__.py
  dragonfly/actions/__init__.py
  dragonfly/actions/action_context.py
  dragonfly/actions/actions.py
Labels: New Feature

#71 WIP - Add more flexible Integer class
  documentation/language.txt
  dragonfly/__init__.py
  dragonfly/language/__init__.py
  dragonfly/language/base/integer.py
  dragonfly/language/en/__init__.py
  dragonfly/language/en/number.py
  dragonfly/language/en/short_number.py
  dragonfly/test/test_language_en_number.py
Labels: Enhancement

#73 Add optional 'remap_data' argument to the Function action
  dragonfly/actions/action_function.py
Labels: Enhancement

#72 Add Key, Text and Paste action support for X11 and Mac OS using pynput
  dragonfly/actions/__init__.py
  dragonfly/actions/_generate_typeables.py
  dragonfly/actions/_test_x11_text_key.py
  dragonfly/actions/action_key.py
  dragonfly/actions/action_paste.py
  dragonfly/actions/action_text.py
  dragonfly/actions/actions.py
  dragonfly/actions/keyboard/__init__.py
  dragonfly/actions/keyboard/_base.py
  dragonfly/actions/keyboard/_pynput.py
  dragonfly/actions/keyboard/_win32.py
  dragonfly/actions/typeables.py
  dragonfly/log.py
  dragonfly/os_dependent_mock.py
  dragonfly/util/clipboard.py
  dragonfly/windows/__init__.py
  setup.py
Labels: Enhancement, Linux, MacOS
