Repository dictation-toolbox/dragonfly, pull requests merged in 2020-12, with the labels that each got.

#313 Add smart type casting to CLI loader engine parameter options
  dragonfly/__main__.py
Labels: Kaldi

#304 Fix Kaldi grammar loading/unloading while in phrase
  dragonfly/engines/backend_kaldi/engine.py
Labels: Bug, Kaldi

#315 Fix recognition observer bug with the KaldiEngine.mimic() method
  dragonfly/engines/backend_kaldi/engine.py
Labels: Bug, Kaldi

#316 Add _functions_example.py example command module
  dragonfly/examples/_functions_example.py
Labels: Documentation

#314 Improve error message when X11 can't be detected
  dragonfly/actions/keyboard/_base.py
Labels: Enhancement, Linux/X11
