Repository dictation-toolbox/dragonfly, pull requests merged in 2020-01, with the labels that each got.

#186 Fix a Windows bug where the wrong mouse buttons may be pressed
  dragonfly/actions/mouse/_win32.py
Labels: Bug, Windows

#187 Minor speed optimizations.
  dragonfly/actions/action_paste.py
  dragonfly/actions/action_text.py
  dragonfly/actions/sendinput.py
Labels: Enhancement, Windows

#188 Fix on_recognition() observer callback for the natlink engine
  dragonfly/engines/backend_natlink/engine.py
  dragonfly/engines/backend_natlink/recobs.py
Labels: Bug, NatLink

#189 Update Kaldi documentation for features in 0.20
  documentation/kaldi_engine.txt
Labels: Documentation, Kaldi

#190 Support running the test suites with different pytest options
  dragonfly/test/suites.py
  setup.py
Labels: Testing

#193 Support focusing windows without raising them on X11
  dragonfly/actions/action_focuswindow.py
  dragonfly/actions/action_startapp.py
  dragonfly/windows/base_window.py
  dragonfly/windows/darwin_window.py
  dragonfly/windows/fake_window.py
  dragonfly/windows/win32_window.py
Labels: Enhancement, Linux

#192 Kaldi updates
  documentation/kaldi_engine.txt
  dragonfly/engines/backend_kaldi/audio.py
  dragonfly/engines/backend_kaldi/engine.py
  dragonfly/engines/backend_kaldi/kag_version.txt
  setup.py
Labels: Documentation, Enhancement, Kaldi

#191 New load & load-directory CLI sub-commands + CLI code cleanup
  documentation/cli.txt
  dragonfly/__main__.py
  dragonfly/loader.py
Labels: New Feature

#195 Fix py2/3 incompatibility for bool
  dragonfly/engines/base/dictation.py
Labels: Bug
