Repository dictation-toolbox/dragonfly, pull requests merged in 2020-02, with the labels that each got.

#197 Add new recognition observers: on_end() and on_post_recognition()
  documentation/recobs.txt
  documentation/test_recobs_doctest.txt
  dragonfly/__init__.py
  dragonfly/engines/backend_kaldi/engine.py
  dragonfly/engines/backend_natlink/engine.py
  dragonfly/engines/backend_natlink/recobs.py
  dragonfly/engines/backend_sapi5/engine.py
  dragonfly/engines/backend_sphinx/engine.py
  dragonfly/engines/backend_sphinx/grammar_wrapper.py
  dragonfly/engines/backend_text/engine.py
  dragonfly/engines/base/engine.py
  dragonfly/engines/base/recobs.py
  dragonfly/grammar/recobs.py
  dragonfly/grammar/recobs_callbacks.py
Labels: New Feature

#198 Add List context manager for optimized updates + List documentation
  documentation/lists.txt
  documentation/object_model.txt
  documentation/rules.txt
  documentation/test_grammar_list_doctest.txt
  dragonfly/grammar/list.py
Labels: Documentation, Enhancement

#201 Change Dragonfly's CLI to expand glob patterns where necessary
  documentation/cli.txt
  dragonfly/__main__.py
Labels: Bug, Windows

#200 Enhance engine dependency checks and log messages
  documentation/conf.py
  dragonfly/engines/__init__.py
  dragonfly/engines/backend_kaldi/__init__.py
  dragonfly/engines/backend_kaldi/engine.py
  dragonfly/engines/backend_natlink/__init__.py
  dragonfly/engines/backend_natlink/engine.py
  dragonfly/engines/backend_sapi5/__init__.py
  dragonfly/engines/backend_sphinx/__init__.py
  dragonfly/engines/backend_sphinx/engine.py
Labels: Enhancement

#202 Fix Function action deprecation warning and add doctests
  documentation/test_action_base_doctest.txt
  dragonfly/actions/action_function.py
Labels: Compatibility, Testing

#156 Catch all exceptions while executing Actions
  dragonfly/actions/action_base.py
Labels: Enhancement

#204 Make some improvements to Dragonfly's macOS support
  dragonfly/actions/action_startapp.py
  dragonfly/windows/darwin_window.py
Labels: Bug, MacOS

#206 Add UnsafeActionSeries class to be used via the | and |= operators
  documentation/test_action_base_doctest.txt
  dragonfly/actions/action_base.py
Labels: Compatibility

#211 Make Kaldi and SAPI5 compilers handle Empty and Impossible elements
  documentation/test_grammar_elements_basic_doctest.txt
  dragonfly/__init__.py
  dragonfly/engines/backend_kaldi/compiler.py
  dragonfly/engines/backend_natlink/engine.py
  dragonfly/engines/backend_sapi5/compiler.py
  dragonfly/engines/backend_sapi5/engine.py
  dragonfly/engines/backend_sphinx/engine.py
  dragonfly/engines/backend_text/engine.py
  dragonfly/grammar/elements_basic.py
Labels: Bug, Kaldi, Windows Speech Recognition

#213 Fix Win32 modifier bug where control could be released if held down
  dragonfly/windows/win32_window.py
Labels: Bug, Windows

#215 Make darwin get_window_module/pid error safe
  dragonfly/windows/darwin_window.py
Labels: Bug, MacOS

#199 Some fixes for the natlink engine and its tests under py3
  documentation/test_word_formatting_v11_doctest.txt
  dragonfly/engines/backend_natlink/dictation_format.py
  dragonfly/engines/backend_natlink/engine.py
Labels: Bug, NatLink
