Repository dictation-toolbox/dragonfly, pull requests merged in 2020-08, with the labels that each got.

#277 Fix bug with BasicRule where it can only be used as a derived class
  dragonfly/grammar/rule_basic.py
  dragonfly/test/suites.py
  dragonfly/test/test_basic_rule.py
Labels: Bug, Testing

#275 Kaldi Update
  documentation/kaldi_engine.txt
  dragonfly/engines/backend_kaldi/audio.py
  dragonfly/engines/backend_kaldi/engine.py
  dragonfly/engines/backend_kaldi/kag_version.txt
Labels: Bug, Enhancement, Kaldi

#276 Fix issues with the get_engine() function
  dragonfly/engines/__init__.py
Labels: Bug

#278 Add high numbers to ShortIntegerRef
  dragonfly/language/en/short_number.py
  dragonfly/test/test_language_en_number.py
Labels: Bug

#279 Minor Kaldi fixes
  documentation/kaldi_engine.txt
  dragonfly/engines/backend_kaldi/engine.py
Labels: Bug, Documentation, Kaldi

#281 Change X11Window.maximize() method to use maximization hints
  README.rst
  documentation/faq.txt
  documentation/installation.txt
  documentation/kaldi_engine.txt
  dragonfly/windows/x11_window.py
Labels: Documentation, Enhancement, Linux/X11

#283 fix Repetition max inaccuracy
  documentation/test_grammar_elements_basic_doctest.txt
  dragonfly/grammar/elements_basic.py
Labels: Bug
