Repository dictation-toolbox/dragonfly, pull requests merged in 2021-04, with the labels that each got.

#328 Update Kaldi backend
  documentation/kaldi_engine.txt
  dragonfly/engines/backend_kaldi/compiler.py
  dragonfly/engines/backend_kaldi/engine.py
  dragonfly/engines/backend_kaldi/kag_version.txt
Labels: Bug, Enhancement, Kaldi

#329 Clipboard toolkit improvements
  README.rst
  documentation/clipboard.txt
  documentation/installation.txt
  documentation/kaldi_engine.txt
  dragonfly/test/test_clipboard.py
  dragonfly/windows/base_clipboard.py
  dragonfly/windows/clipboard.py
  dragonfly/windows/pyperclip_clipboard.py
  dragonfly/windows/win32_clipboard.py
  dragonfly/windows/x11_clipboard.py
Labels: Enhancement, Linux/X11

#332 get_engine() function changes
  dragonfly/engines/__init__.py
Labels: CMU Pocket Sphinx, Documentation, Enhancement, Kaldi, Windows Speech Recognition

#333 Fix leak of file open() without close.
  dragonfly/config.py
Labels: Bug

#334 Change keyboard-related import-time side-effects
  dragonfly/actions/action_base_keyboard.py
  dragonfly/actions/action_paste.py
Labels: Windows

#331 Change the Choice element class to allow using list/tuple choices
  documentation/elements.txt
  documentation/object_model.txt
  dragonfly/grammar/elements_compound.py
Labels: Documentation, Enhancement

#336 Improve Windows keyboard action support for letter and number keys
  dragonfly/actions/action_key.py
  dragonfly/actions/action_paste.py
  dragonfly/actions/action_text.py
  dragonfly/actions/keyboard/_win32.py
Labels: Bug, Enhancement, Windows
