Repository dictation-toolbox/dragonfly, pull requests merged in 2021-02, with the labels that each got.

#320 Fix smart casting for CLI to handle other possible exceptions for som…
  dragonfly/__main__.py
Labels: Bug

#321 Change German integer impl. to support compound words in range 20-99
  dragonfly/language/base/integer.py
  dragonfly/language/base/integer_internal.py
  dragonfly/language/de/number.py
  dragonfly/test/test_language_de_number.py
Labels: Bug, Enhancement

#319 Fix clipboard incorrect handling of None type
  dragonfly/util/clipboard.py
  dragonfly/windows/clipboard.py
Labels: Bug

#324 Travis CI: Test on current versions of Python
  .travis.yml
Labels: Testing
